// <auto-generated />
using System;
using IntelliCampus.Presistence.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntelliCampus.DAL.Migrations
{
    [DbContext(typeof(IntelliCampusDbContext))]
    [Migration("20260612120000_AddLocationAndPriorityToReminders")]
    partial class AddLocationAndPriorityToReminders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // NOTE: Full model snapshot omitted; EF uses IntelliCampusDbContextModelSnapshot for the complete model.
            // This designer exists to satisfy build-time migration metadata.
#pragma warning restore 612, 618
        }
    }
}
